### ISSUE TITLE
Theme changer not working (Windows 7)

### ISSUE THREAD

**Issue by JPhB** [peter88213/novelyst_themes#1] opened 2023-01-01 03:30 UTC
Extracting the Theme Changer zip file in Windows 7 gives a Headers error. Theme Changer appears in Tools, but the window has nothing in it. 

![theme](https://user-images.githubusercontent.com/39348213/210160234-ab255e88-f850-44aa-a44f-d3e8dca37bfd.JPG)

**Comment by peter88213** [comment] 2023-01-01 10:14
I downloaded the file, and it can be opened by 7zip version 18.0.5 without any problems. When creating the zipfile there is also no difference to all my other projects. 

Also does not let you open it in Windows Explorer? I can even open the downloaded archive under vista with the file manager. 
Could it be that something went wrong with the download? Maybe download again.

If that doesn't help, maybe get the distribution [directly from the project site](https://github.com/peter88213/novelyst_themes/tree/main/dist) (although technically that shouldn't make a difference).

In general: Please report plugin bugs on the respective plugin page. In the novelyst plugin manager (tools menu) there is a button to open the homepage for the selected Plugin, which is intended for updates.

**Comment by peter88213** [comment] 2023-01-01 11:01
Is it perhaps possible that you tried to run the setup script from the packed archive? Something like that can't work.

**Comment by JPhB** [comment] 2023-01-01 13:33
The archive opens and unpacks. As I mentioned, Theme Changer appears in Tools. But it's empty.

![them](https://user-images.githubusercontent.com/39348213/210172330-bd0a6f0d-d332-44fb-b02e-ec29d0e8d1ce.JPG)

**Comment by peter88213** [comment] 2023-01-01 13:35
> Theme Changer appears in Tools, but the window has nothing in it.

So this is a real bug that is not related to the "cannot unpack" problem (which should be solved, if you actually have installed the plugin). 

The available themes are not displayed, because the [ttkthemes package](https://ttkthemes.readthedocs.io/en/latest/installation.html) is not installed, like in the testing environment, and the default theme list is not exactly compatible. This will be fixed with v4.0.2.

Technical details:
ttkthemes.ThemedStyle.theme_names() returns a list, whereas ttk.Style.theme_names() returns a tuple, which has no sort() method. On trying to sort the themes, the display routine exits, leaving the window empty. The problem is fixed by typecasting the theme_names() return value.

**Closed as completed** 2023-01-01 13:35 UTC

**Comment by JPhB** [comment] 2023-01-01 13:40
OK Thanks. You're right, this was not a "cannot unpack" problem.

**Comment by JPhB** [comment] 2023-01-02 14:19
It works now with updated versions. Thanks

**Comment by peter88213** [comment] 2023-01-02 15:00
Actually, the plugin is more intended for Linux, where the default theme looks pretty stale, and there are plenty of desktops, each with a different look. 

On Windows, *novelyst* uses a lot of native widgets by default, you can hardly do better with custom themes. 
However, if you want a dark theme, another plugin is good for that, which I included with the novelyst add-ons (awdark). That also changes the colors of the tree entries. However, it must not be installed at the same time as this *novelyst_themes* plugin.

**Comment by JPhB** [comment] 2023-01-02 15:03
>you can hardly do better with custom theme

True. I was just curious to see it work. Native Windows is fine.
